feat: add olares cli content
beclab/docs pull request #75
Opened 2024-12-06 13:37 UTC by fnalways

This PR adds Olares CLI docs.

2024-12-11 12:44 UTC, dkeven requested changes

2024-12-11 12:44 UTC, dkeven commented on docs/developer/develop/advanced/cli/olares-change-ip.md
> +:::warning When manually changing IP address is required
why should this notice be a "warning"?
and update: the IP is now automatically retrieved and the user only have to confirm it.

2024-12-11 12:44 UTC, dkeven commented on docs/developer/develop/advanced/cli/olares-change-ip.md
> +- **macOS**: Olares runs in containers and relies on stable IPs. If your Mac's network settings change (e.g., switching Wi-Fi), Olares won't adjust the IP automatically, which may disrupt DNS resolut
these two need amendment

2024-12-11 12:44 UTC, dkeven commented on docs/manual/concepts/data.md
> +By default, Olares OS uses MinIO as object storage when installed locally. Initial installation starts with [Single Node Single Driver (SNSD)](https://min.io/docs/minio/linux/operations/install-deplo
MinIO and JuiceFS are now disabled by default and not installed, to enable it a new option need to be specified.

2024-12-11 12:44 UTC, dkeven commented on docs/manual/help/faqs.md
> +Yes. You can refer to [How to add a node](../../developer/develop/advanced/cli/cli#add-an-olares-node-locally).
it's not supported for the time being.

2024-12-11 12:44 UTC, dkeven commented on docs/developer/develop/advanced/cli/olares-install.md
> +| `--manifest` |           | Set the path to the manifest file, which contains metadata about the installation packages and configuration. <br> Defaults to `{base-dir}/versions/v{version}/installatio
the `manifest` option in all commands is now removed

2024-12-11 12:44 UTC, dkeven commented on docs/developer/develop/advanced/cli/olares-prepare.md
> +The `olares prepare` command sets up the environment required for Olares to function. This includes installing core services, importing container images, and starting the Olares daemon (`olaresd`).
installing "core services" seems duplicate with the install phase, "dependencies" may be a better description.

2024-12-11 12:44 UTC, dkeven commented on docs/developer/develop/advanced/cli/olares-uninstall.md
> +| `--all`      |           | Uninstall Olares completely, including dependencies downloaded during the "prepare" phase.
it's not "downloaded", should be "installed"

2024-12-11 13:18 UTC, fnalways commented on docs/developer/develop/advanced/cli/olares-change-ip.md
> +:::warning When manually changing IP address is required
> why should this notice be a "warning"? 
Only because of its color. The less prominent version, "info," is gray and might not catch the user's attention effectively. Or we should go with gray and try to lay low for this notel? XD
> and update: the IP is now automatically retrieved and the user only have to confirm it.
Good to know! Will update the doc in get-started section.

2024-12-12 05:51 UTC, cal-weng commented on docs/developer/develop/advanced/cli/olares-cli.md
> +While the initial script handles downloading `olares-cli`, the tool itself is responsible for the actual installation and configuration of Olares. The process typically involves the following phases:
```suggestion
Olares provides Olares CLI, a command-line tool for developers and system administrators to customize or troubleshoot the Olares installation process.

The recommended [one-liner installation command](https://docs.olares.xyz/manual/get-started/install-olares.html#install-olares) retrieves a shell script from https://olares.sh/ that downloads and installs Olares CLI. Once installed, the CLI orchestrates the remainder of the setup.

In general, Olares CLI manages installation through three main phases:
```

2024-12-13 06:13 UTC, fnalways commented on docs/developer/develop/advanced/cli/olares-cli.md
> +For example, if you use the `--base-dir` option with `olares-cli olares download`, it will only affect the download process and will not change the base directory for other commands, such as during t
Indeed. But explicitly stating it can help avoid confusion and ensure that users understand the behavior clearly.

2024-12-13 07:50 UTC, cal-weng approved these changes

2024-12-13 08:15 UTC, dkeven requested changes

2024-12-13 09:16 UTC, fnalways commented
@dkeven PTAL, thanks!

2024-12-13 09:41 UTC, dkeven approved these changes

2024-12-13 09:43 UTC, merged