feat: restructure installation and add PVE
beclab/docs pull request #85
Opened 2024-12-20 09:27 UTC by cal-weng

- [x] add guides for PVE and LXC on PVE
- [x] Merge or Linux based systems  
- [x] edit related config files

2024-12-20 13:37 UTC, fnalways requested changes
The on-page toc does not update when switching sub-tabs. Do not merge this PR until it's fixed.

2024-12-23 03:22 UTC, cal-weng commented on docs/manual/get-started/install-olares-linux.md
> +   If you want to install Olares on an existing LXC container. Skip to step 2 directly. Make sure you use the corresponding container ID.
```suggestion
To install Olares on an existing LXC container, skip to step 2 directly. Make sure you use the corresponding container ID.
```

2024-12-24 04:05 UTC, fnalways reviewed
Comments also apply to chinese docs.

2024-12-24 04:05 UTC, fnalways commented on docs/manual/get-started/install-olares-general-linux.md
> +   ![Enter password](/images/manual/get-started/enter-root-user-password.png)
In chinese version, we use note for this step. Should we align here (and also for other linux-based system)?

2024-12-24 04:05 UTC, fnalways commented on docs/zh/manual/get-started/install-olares-lxc.md
> +      ```
Adjust indentation

2024-12-24 05:23 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-lxc.md
> +   ::: tip 提示
```suggestion
   ::: tip 安装至已有 LXC 容器
```

2024-12-24 05:24 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-lxc.md
> +      ```
```suggestion
   ```bash 
   # 启动容器
   pct start 16553

   # 进入容器
   pct enter 16553

   # 创建缺失的目录
   mkdir -p /lib/modules

   # 更新 PATH 环境变量
   echo 'export PATH="/usr/local/bin:$PATH"' >> /root/.bashrc
   source ~/.bashrc
      
   # 退出 LXC
   exit
   ```
```

2024-12-24 05:37 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-lxc.md
> +   ::: tip 注意
```suggestion
   ::: tip 指定唯一容器 ID
```

2024-12-24 05:37 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-lxc.md
> +::: tip 注意
```suggestion
::: tip 版本兼容性
```

2024-12-24 05:38 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-pve.md
> +::: tip 注意
```suggestion
::: tip 版本兼容性
```

2024-12-24 05:39 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-general-linux.md
> +::: tip 注意
```suggestion
::: tip 版本兼容性
```

2024-12-24 05:45 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-lxc.md
> +## <span class="h2-border-none">系统要求</span>
```suggestion
## <span class="h2-border-none">系统要求</span>

LXC（Linux 容器）是一种轻量级的虚拟化技术，可以在隔离的容器中运行应用程序。在 PVE 环境下使用 LXC 部署 Olares 能够避免完整虚拟机的额外开销，提供了一种更高效的部署方式。
```

2024-12-24 05:57 UTC, cal-weng commented on docs/manual/get-started/install-olares-lxc.md
> +    - Linus container: Debian 12 (for existing LXC containers on PVE)
```suggestion
    - Linux container: Debian 12 (for existing LXC containers on PVE)
```

2024-12-24 05:58 UTC, cal-weng commented on docs/zh/manual/get-started/install-olares-lxc.md
> +  - LXC 系统：Debian 12
```suggestion
  - LXC 容器系统：Debian 12
```

2024-12-24 07:12 UTC, fnalways approved these changes

2024-12-24 07:55 UTC, merged